// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAisqZYgG2fXLXj5nJorow-Rv9DQQFFZYY',
    appId: '1:774482243258:web:e9cf494f66e5c9536a9c83',
    messagingSenderId: '774482243258',
    projectId: 'innjoy-b0815',
    authDomain: 'innjoy-b0815.firebaseapp.com',
    storageBucket: 'innjoy-b0815.firebasestorage.app',
    measurementId: 'G-GCZJQP72X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtlRAtz2Z2Wa0i5ecFkGruv_BCFp3L-ds',
    appId: '1:774482243258:android:5cbb44b073d880e46a9c83',
    messagingSenderId: '774482243258',
    projectId: 'innjoy-b0815',
    storageBucket: 'innjoy-b0815.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8nbw3rpnUvhiRiwHHnUGYRDPeCRHvKzk',
    appId: '1:774482243258:ios:fbc77a294022760c6a9c83',
    messagingSenderId: '774482243258',
    projectId: 'innjoy-b0815',
    storageBucket: 'innjoy-b0815.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8nbw3rpnUvhiRiwHHnUGYRDPeCRHvKzk',
    appId: '1:774482243258:ios:fbc77a294022760c6a9c83',
    messagingSenderId: '774482243258',
    projectId: 'innjoy-b0815',
    storageBucket: 'innjoy-b0815.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAisqZYgG2fXLXj5nJorow-Rv9DQQFFZYY',
    appId: '1:774482243258:web:aec5da31880597c46a9c83',
    messagingSenderId: '774482243258',
    projectId: 'innjoy-b0815',
    authDomain: 'innjoy-b0815.firebaseapp.com',
    storageBucket: 'innjoy-b0815.firebasestorage.app',
    measurementId: 'G-JKK79VQ2D3',
  );
}








